title: Find Your EV
email: oakeef@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Find the perfect new or used BEV or PHEV for you with the tools available on this site.
  Search through dymanic lists for different price ranges or do a custom search
  based off of your own personal needs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: stuffwithevan
github_username:  oakeef

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed