# Site
name: "Find Your EV Canada"
title: "Find Your EV Canada"
description: "The best way for Canadians to find the right EV for them"
meta_description: "Help Canadians find Electric Vehicles"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 8
baseurl: ''
email: 'oakeef@gmail.com'
google_analytics: ''
disqus: ''
sharethis: '<script async src="//platform-api.sharethis.com/js/sharethis.js#property=5c8edb731c07550011f24ea4&product="sticky-share-buttons"></script>'

# Authors
authors:
  evan:
    name: Evan
    display_name: Evan
    gravatar: 50dcc30c6d36035c211e2ff671722333
    email: oakeef@gmail.com
    web: 
    twitter: https://twitter.com/stuffwithevan
    description: "Evan loves all cars, especially EVs"
  author2:
    name: 
    display_name: 
    gravatar: 
    email: 
    web: 
    twitter: 
    description: 

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge